project:
  type: website
  output-dir: docs

website:
  title: "Kierst01.github.io.git"
  navbar:
    left:
      - href: index.qmd
        text: Main page
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



