project:
  type: website
  output-dir: docs

website:
  title: "Kiersten Pinsky"
  navbar:
    background: dark
    search: true
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/kiersten-pinsky/
      - icon: github
        href: https://github.com/kierst01
      - icon: envelope
        text: Email
        href: mailto:kierstengilberg@gmail.com
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
  page-footer: 
    left: "Copyright 2024, Kiersten Pinsky" 

format:
  html:
    theme: Journal
    css: styles.css
    toc: true
    mainfont: sans-serif
    #fontcolor: "#605d5d"
